// Auto-generated by updateCharacters.py
// Import all exported characters from the module version
import * as Characters from "./characterList.module.js";

// Expose read-only globals for convenience authoring
for (const [name, obj] of Object.entries(Characters)) {
  if (!(name in globalThis)) {
    Object.defineProperty(globalThis, name, {
      value: obj,
      writable: false,
      configurable: false,
      enumerable: true
    });
  }
}

// Also export default registry if you ever want to import it
export default Characters;
