// Auto-generated by updateBits.py
// Import all exported bits from the module version
import * as Bits from "./bitList.module.js";

// Expose read-only globals for convenience authoring
for (const [name, obj] of Object.entries(Bits)) {
  if (!(name in globalThis)) {
    Object.defineProperty(globalThis, name, {
      value: obj,
      writable: false,
      configurable: false,
      enumerable: true,
    });
  }
}

// Also export default registry if you ever want to import it
export default Bits;
