// Auto-generated by updateBits.py
import type { Bit } from "../classes/bit.js";
declare global {
  const doMuch: Bit;
  const gonnaDo: Bit;
  const wellConditionally: Bit;
  const whatchaDoin: Bit;
  const wherePerry: Bit;
  const lindana: Bit;
  const littleYoung: Bit;
  const andBy: Bit;
  const bird: Bit;
  const curseYou: Bit;
  const aPlatypus: Bit;
  const ohTherePerry: Bit;
  const selfDestruct: Bit;
  const ggg: Bit;
  const quirkyWorky: Bit;
  const pharmacist: Bit;
  const farmer: Bit;
  const fthWall: Bit;
  const isOUT: Bit;
}
export {};
