import "../../characters/globals.js";
import { Episode } from "../../classes/episode.js";
import { Song } from "../../classes/song.js";
import { Connection } from "../../classes/connection.js";
import "../../bits/globals.js";
import { Bit } from "../../classes/bit.js";
import { connectAll, groupConnections } from "../connectionHelpers.js";

export const ep113 = new Episode({
  number: 113,
  code: "239",
  title: "Rollercoaster: The Musical!",
  aPlot: "Rollercoaster [the musical!]",
  bPlot: "Magnetism Magnifinator",
  songs: [new Song("Hey Ferb", [Phineas]), new Song("You're Going Down", [Candace, Stacy, Jenny]), new Song("Whatcha Doin'?", [Isabella, Katie, Milly, Gretchen, Holly]), new Song("Monogram Box Song", [Monogram]),
  new Song("Mom Look", [Candace]), new Song("Aren't You a Little Young", [BEngineer, Phineas]), new Song("Back in Gimmelshtump", [Doof]), new Song("Rollercoaster", [Phineas, Ferb, Buford]), new Song("Carpe Diem", [Phineas, Ferb, Isabella, Candace, Buford, Katie, Milly, Ginger, Holly, Adyson, Gretchen, Bobbi, Sherman, DannyLH,])],
  characters: [
    Phineas,
    Ferb,
    Perry,
    Linda,
    Candace,
    Stacy,
    Jenny,
    GFBH,
    Isabella,
    Katie,
    Milly,
    Gretchen,
    Holly,
    Monogram,
    Doof,
    Carl,
    BEngineer,
    Charlene,
    Norm,
    Pedro,
    Dimitri,
    DumbassGinger,
    Buford,
    Sam,
    Chalk,
    Logan,
    Chaw,
    Baljeet,
    Farmer,
    FarmerWife,
    Adyson,
    Meap,
    Greg,
    Gerez,
    Lawrence,
    Winifred,
    Reginald,
    Coltrane,
    KennyOrtega,
    DoofMom,
    DoofDad,
    Roger,
    Kenny,
    Mitch,
    Balloony,
    Marty,
    Baxter,
    Jerry,
    Martians,
    Blayn,
    Clewnt,
    Santa,
    AgentLizard,
    AgentHedgehog,
    AgentOwl,
    AgentRacoon2,
    AgentChicken,
    StacyCousins,
    DannyLH,
    Sherman,
    Bobbi,
    Badinkadink,
    Mishti,
    Regurgitator,
    Destructicon,
    Haney,
    TalkingZebra,
    Poofenplotz,
    AgentFrog,
    AgentKangaroo,
    AgentPanda,
    AgentDog,
    Pinky,
    Dave,
    Rick,
    SamAdult,
    Irving,
    Suzy,
    Django,
    Vivian,
    Biffany,
    Gevaarlijk,
    DrillSergeant,
    Wendy
  ],
  interactions: [
    connectAll([Perry, Monogram, Carl], 6),
    connectAll([Phineas, Ferb, Perry], 6),
    connectAll([Candace, Stacy, Jenny, Isabella], 6),
    connectAll([Isabella, Katie, Milly, Holly, Ginger], 6),
    connectAll([Buford, Dimitri, Pedro, DumbassGinger], 6),
    connectAll([Chalk, Sam, Pedro, Logan, DumbassGinger], 1),
    connectAll([Ginger, Katie, Pedro, Dimitri, Terrance, Chalk, Chaw, Isabella], 1),
    connectAll([Phineas, Ferb, Isabella, Baljeet, Buford, Katie, Milly, Holly, Gretchen, Adyson], 6),
    connectAll([Phineas, Ferb, Isabella, Baljeet, Buford, Katie, Milly, Holly, Gretchen, Adyson, Greg, Gerez, Linda, Lawrence, Monogram, Carl, Winifred, Reginald, Doof, Perry, Candace, Jeremy, Stacy, Coltrane, BettyJo, Clyde, Vanessa, Ginger,], 1),
    connectAll([Doof, DoofDad, DoofMom, Kenny, Roger], 6),
    connectAll([Mitch, Meap, Balloony], 6),
    connectAll([Marty, Jerry, Baxter], 6),
    connectAll([Blayn, Clewnt, Santa, AgentLizard, AgentHedgehog, AgentOwl, AgentRacoon2, AgentChicken], 6),
    connectAll([Phineas, Ferb, DannyLH, Bobbi, Sherman], 6),
    connectAll([AgentKangaroo, AgentFrog, AgentPanda, AgentDog, Pinky], 6),
    connectAll([Dave, Rick, Charlene, Roger, SamAdult, Doof, Linda, Lawrence, Buford, Isabella, Candace, Phineas, Ferb, Jeremy, Stacy, Coltrane, Baljeet, Irving], 1),
    connectAll([Phineas, Ferb, Irving, Baljeet, Mishti, Suzy, Django, Vivian, Linda, Lawrence, Haney, Charlene, Pinky, AgentRacoon2, AgentPig, AgentDof, Candace, Jeremy, Stacy, Coltrane, Bobbi, DannyLH, Ginger, Reginald, Winifred, Biffany, BettyJo, Clyde, Gevaarlijk, DrillSergeant, GFBH, Katie, Milly, Ginger, Holly, Adyson, Gretchen, Vanessa, Doof, Pedro, Buford, Wendy, Perry, Greg], 1),

    groupConnections([Phineas, Ferb, Perry], [Linda, Candace, GFBH], 6),
    groupConnections([Phineas, Ferb], [Jenny, Stacy], 3),
    groupConnections([Ferb], [Chaw, Chalk, Pedro, Katie, Terrance, Ginger], 6),
    groupConnections([Ginger, Katie, Pedro, Dimitri, Terrance, Chalk, Chaw], [Phineas], 3),
    groupConnections([Ferb, Isabella, Ginger, Buford, Baljeet, Milly, Gretchen, Holly, Adyson, Katie, Chalk], [Jeremy, Meap], 3),
    groupConnections([Jeremy, Candace, Greg, Katie, Milly, Ginger, Adyson, Gretchen, Isabella, Buford, Baljeet], [KennyOrtega], 3),
    groupConnections([KennyOrtega], [Jeremy, Candace, Greg, Katie, Milly, Ginger, Adyson, Gretchen, Isabella, Buford, Baljeet], 3),

    new Connection(Monogram, Doof, 4),
    new Connection(Perry, Doof, 6),
    new Connection(Linda, Candace, 6),
    new Connection(Candace, Stacy, 6),
    new Connection(Stacy, [Linda, Phineas, Ferb], 2),
    new Connection(Phineas, Stacy, 4),
    new Connection(Isabella, Perry, 2),
    new Connection(BEngineer, Phineas, 6),
    new Connection(Doof, Charlene, 4),
    new Connection(Perry, Charlene, 2),
    new Connection(Baljeet, Buford, 6),
    new Connection(Phineas, Baljeet, 6),
    new Connection(Farmer, FarmerWife, 6),
    new Connection(Phineas, Jeremy, 6),
    new Connection(Jeremy, Candace, 4),
    new Connection(Phineas, Meap, 3),
    new Connection(Winifred, Reginald, 6),
    new Connection(Phineas, KennyOrtega, 6),
    new Connection(Baljeet, Mishti, 6),
    new Connection(Destructicon, Regurgitator, 6),
    new Connection(Linda, Lawrence, 6),
  ],
  bits: [gonnaDo, wellConditionally, whatchaDoin, wherePerry, littleYoung, andBy, bird, farmer, curseYou, ohTherePerry],
  ferbLines: 3, 
});

//#region Bit Handler
gonnaDo.addModifiedAppearance(ep113, Phineas);
wellConditionally.addAppearance(ep113, Candace);
whatchaDoin.addModifiedAppearance(ep113, Isabella);
wherePerry.addAppearance(ep113, Phineas);
littleYoung.addModifiedAppearance(ep113, Linda);
andBy.addModifiedAppearance(ep113, Doof);
bird.addAppearance(ep113);
farmer.addAppearance(ep113);
curseYou.addModifiedAppearance(ep113, Doof);
ohTherePerry.addAppearance(ep113, Phineas);
//#endregion
